#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

# Utility functions

file_exists() {
    test -f "$1"
}

directory_exists() {
    test -d "$1"
}

# Operations

xdg_variables() {
    if ! file_exists "/etc/profile.d/xdg.sh"; then
        echo 'Setting up XDG environement variables...'
        sudo ln -s "$HOME/.config/zsh/xdg.sh" "/etc/profile.d/xdg.sh"
        echo 'Done.'
    fi
}

neovim_package_manager() {
    if ! directory_exists "$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim"; then
        echo 'Installing a package manager for Neovim...'
        git clone "https://github.com/wbthomason/packer.nvim" "$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim"
        echo 'Done.'
    fi
}

neovim_packages() {
    nvim --headless +PackerSync +qa
}

main() {
    xdg_variables
    neovim_package_manager
    neovim_packages
    exit 0
}

main
