#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

# Utility functions

file_exists() {
    test -f "$1"
}

directory_exists() {
    test -d "$1"
}

# Operations

xdg_variables() {
    if ! file_exists "/etc/profile.d/xdg.sh"; then
        echo 'Setting up XDG environement variables...'
        sudo ln -s "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/xdg.sh" "/etc/profile.d/xdg.sh"
        echo 'Done.'
    fi
}

neovim_package_manager() {
    PACKER_DIRECTORY="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/pack/packer/start/packer.nvim"

    if ! directory_exists "$PACKER_DIRECTORY"; then
        echo 'Installing a package manager for Neovim...'
        git clone "https://github.com/wbthomason/packer.nvim" "$PACKER_DIRECTORY"
        echo 'Done.'
    fi
}

neovim_packages() {
    nvim -u NONE \
        +'autocmd User PackerComplete quitall' \
        +'lua require("my.config.packages")' \
        +'lua require("packer").sync()'
}

main() {
    xdg_variables
    neovim_package_manager
    neovim_packages
    exit 0
}

main
