#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

# Utility functions

file_exists() {
    test -f "$1"
}

directory_exists() {
    test -d "$1"
}

# Operations

neovim_package_manager() {
    local PAQ_DIRECTORY="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/paq/paq/start/pack"

    if ! directory_exists "$PAQ_DIRECTORY"; then
        echo 'Installing a package manager for Neovim...'
        git clone "https://github.com/savq/paq-nvim" "$PAQ_DIRECTORY"
        echo 'Done.'
    fi
}

neovim_packages() {
    nvim -u NONE \
        +'autocmd User PaqDoneSync quitall' \
        +'lua require("my.config.packages")' \
        +'lua require("paq"):sync()'
}

main() {
    neovim_package_manager
    neovim_packages
    exit 0
}

main
